### ISSUE TITLE
Logo in Refreshed does not load

### ISSUE THREAD

**Issue by Daniel4-Scratch** [snapwiki/issues#1]
**Describe the bug**
The wiki logo in the Refreshed theme does not load.

**To Reproduce**
1. change theme to 'Refreshed'
2. The logo will not load

**Expected behavior**
The Logo should show.
**Screenshots**
![Screen Shot 2020-10-03 at 9 25 55 am](https://user-images.githubusercontent.com/65277548/94977059-726eed80-055a-11eb-94ed-829fec8e802b.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version newest

**Comment by R4356th** [comment]
Thank you for reporting this. I have created a [Phabricator task](https://phabricator.miraheze.org/T6268) about this.

**Comment by R4356th** [comment]
This is not a bug; rather just a configuration issue.

**Comment by R4356th** [comment]
I have disabled Refreshed skin because it was not working.
