### ISSUE TITLE
Suck on a theme

### ISSUE THREAD

**Issue by Daniel4-Scratch** [snapwiki/issues#2]
**Describe the bug**
Can't change theme back to vector. There is no preferences link.

**To Reproduce**
I forgot which theme but here's a pic:
![Screen Shot 2020-10-08 at 8 40 08 am](https://user-images.githubusercontent.com/65277548/95390985-f43b8e00-0941-11eb-82c6-fbe4849a3784.png)

**Expected behavior**
Should have a clear link to preferences and ect.

**Comment by R4356th** [comment]
This is not a bug since a skin may not include all the links included in Vector. You can always change your preferences [here](https://snapwiki.miraheze.org/wiki/Special:Preferences).
